using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;

namespace Anthropic.Models.Beta.Messages;

/// <summary>
/// Tool invocation generated by a server-side tool.
/// </summary>
[JsonConverter(typeof(ModelConverter<BetaServerToolCaller, BetaServerToolCallerFromRaw>))]
public sealed record class BetaServerToolCaller : ModelBase
{
    public required string ToolID
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "tool_id"); }
        init { ModelBase.Set(this._rawData, "tool_id", value); }
    }

    public JsonElement Type
    {
        get { return ModelBase.GetNotNullStruct<JsonElement>(this.RawData, "type"); }
        init { ModelBase.Set(this._rawData, "type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ToolID;
        if (
            !JsonElement.DeepEquals(
                this.Type,
                JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"")
            )
        )
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
    }

    public BetaServerToolCaller()
    {
        this.Type = JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"");
    }

    public BetaServerToolCaller(BetaServerToolCaller betaServerToolCaller)
        : base(betaServerToolCaller) { }

    public BetaServerToolCaller(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];

        this.Type = JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    BetaServerToolCaller(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="BetaServerToolCallerFromRaw.FromRawUnchecked"/>
    public static BetaServerToolCaller FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public BetaServerToolCaller(string toolID)
        : this()
    {
        this.ToolID = toolID;
    }
}

class BetaServerToolCallerFromRaw : IFromRaw<BetaServerToolCaller>
{
    /// <inheritdoc/>
    public BetaServerToolCaller FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => BetaServerToolCaller.FromRawUnchecked(rawData);
}
