using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;

namespace Anthropic.Models.Beta.Messages;

/// <summary>
/// Tool invocation generated by a server-side tool.
/// </summary>
[JsonConverter(typeof(ModelConverter<BetaServerToolCaller>))]
public sealed record class BetaServerToolCaller : ModelBase, IFromRaw<BetaServerToolCaller>
{
    public required string ToolID
    {
        get
        {
            if (!this._rawData.TryGetValue("tool_id", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'tool_id' cannot be null",
                    new ArgumentOutOfRangeException("tool_id", "Missing required argument")
                );

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new AnthropicInvalidDataException(
                    "'tool_id' cannot be null",
                    new ArgumentNullException("tool_id")
                );
        }
        init
        {
            this._rawData["tool_id"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public JsonElement Type
    {
        get
        {
            if (!this._rawData.TryGetValue("type", out JsonElement element))
                throw new AnthropicInvalidDataException(
                    "'type' cannot be null",
                    new ArgumentOutOfRangeException("type", "Missing required argument")
                );

            return JsonSerializer.Deserialize<JsonElement>(element, ModelBase.SerializerOptions);
        }
        init
        {
            this._rawData["type"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public override void Validate()
    {
        _ = this.ToolID;
        if (
            !JsonElement.DeepEquals(
                this.Type,
                JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"")
            )
        )
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
    }

    public BetaServerToolCaller()
    {
        this.Type = JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"");
    }

    public BetaServerToolCaller(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];

        this.Type = JsonSerializer.Deserialize<JsonElement>("\"code_execution_20250825\"");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    BetaServerToolCaller(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    public static BetaServerToolCaller FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public BetaServerToolCaller(string toolID)
        : this()
    {
        this.ToolID = toolID;
    }
}
