using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Anthropic.Core;
using Anthropic.Exceptions;
using Anthropic.Models.Messages;

namespace Anthropic.Models.Beta.Messages;

[JsonConverter(typeof(ModelConverter<BetaMessage, BetaMessageFromRaw>))]
public sealed record class BetaMessage : ModelBase
{
    /// <summary>
    /// Unique object identifier.
    ///
    /// <para>The format and length of IDs may change over time.</para>
    /// </summary>
    public required string ID
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "id"); }
        init { ModelBase.Set(this._rawData, "id", value); }
    }

    /// <summary>
    /// Information about the container used in the request (for the code execution tool)
    /// </summary>
    public required BetaContainer? Container
    {
        get { return ModelBase.GetNullableClass<BetaContainer>(this.RawData, "container"); }
        init { ModelBase.Set(this._rawData, "container", value); }
    }

    /// <summary>
    /// Content generated by the model.
    ///
    /// <para>This is an array of content blocks, each of which has a `type` that
    /// determines its shape.</para>
    ///
    /// <para>Example:</para>
    ///
    /// <para>```json [{"type": "text", "text": "Hi, I'm Claude."}] ```</para>
    ///
    /// <para>If the request input `messages` ended with an `assistant` turn, then
    /// the response `content` will continue directly from that last turn. You can
    /// use this to constrain the model's output.</para>
    ///
    /// <para>For example, if the input `messages` were: ```json [   {"role": "user",
    /// "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},
    ///   {"role": "assistant", "content": "The best answer is ("} ] ```</para>
    ///
    /// <para>Then the response `content` might be:</para>
    ///
    /// <para>```json [{"type": "text", "text": "B)"}] ```</para>
    /// </summary>
    public required IReadOnlyList<BetaContentBlock> Content
    {
        get { return ModelBase.GetNotNullClass<List<BetaContentBlock>>(this.RawData, "content"); }
        init { ModelBase.Set(this._rawData, "content", value); }
    }

    /// <summary>
    /// Context management response.
    ///
    /// <para>Information about context management strategies applied during the request.</para>
    /// </summary>
    public required BetaContextManagementResponse? ContextManagement
    {
        get
        {
            return ModelBase.GetNullableClass<BetaContextManagementResponse>(
                this.RawData,
                "context_management"
            );
        }
        init { ModelBase.Set(this._rawData, "context_management", value); }
    }

    /// <summary>
    /// The model that will complete your prompt.\n\nSee [models](https://docs.anthropic.com/en/docs/models-overview)
    /// for additional details and options.
    /// </summary>
    public required ApiEnum<string, Model> Model
    {
        get { return ModelBase.GetNotNullClass<ApiEnum<string, Model>>(this.RawData, "model"); }
        init { ModelBase.Set(this._rawData, "model", value); }
    }

    /// <summary>
    /// Conversational role of the generated message.
    ///
    /// <para>This will always be `"assistant"`.</para>
    /// </summary>
    public JsonElement Role
    {
        get { return ModelBase.GetNotNullStruct<JsonElement>(this.RawData, "role"); }
        init { ModelBase.Set(this._rawData, "role", value); }
    }

    /// <summary>
    /// The reason that we stopped.
    ///
    /// <para>This may be one the following values: * `"end_turn"`: the model reached
    /// a natural stopping point * `"max_tokens"`: we exceeded the requested `max_tokens`
    /// or the model's maximum * `"stop_sequence"`: one of your provided custom `stop_sequences`
    /// was generated * `"tool_use"`: the model invoked one or more tools * `"pause_turn"`:
    /// we paused a long-running turn. You may provide the response back as-is in
    /// a subsequent request to let the model continue. * `"refusal"`: when streaming
    /// classifiers intervene to handle potential policy violations</para>
    ///
    /// <para>In non-streaming mode this value is always non-null. In streaming mode,
    /// it is null in the `message_start` event and non-null otherwise.</para>
    /// </summary>
    public required ApiEnum<string, BetaStopReason>? StopReason
    {
        get
        {
            return ModelBase.GetNullableClass<ApiEnum<string, BetaStopReason>>(
                this.RawData,
                "stop_reason"
            );
        }
        init { ModelBase.Set(this._rawData, "stop_reason", value); }
    }

    /// <summary>
    /// Which custom stop sequence was generated, if any.
    ///
    /// <para>This value will be a non-null string if one of your custom stop sequences
    /// was generated.</para>
    /// </summary>
    public required string? StopSequence
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "stop_sequence"); }
        init { ModelBase.Set(this._rawData, "stop_sequence", value); }
    }

    /// <summary>
    /// Object type.
    ///
    /// <para>For Messages, this is always `"message"`.</para>
    /// </summary>
    public JsonElement Type
    {
        get { return ModelBase.GetNotNullStruct<JsonElement>(this.RawData, "type"); }
        init { ModelBase.Set(this._rawData, "type", value); }
    }

    /// <summary>
    /// Billing and rate-limit usage.
    ///
    /// <para>Anthropic's API bills and rate-limits by token counts, as tokens represent
    /// the underlying cost to our systems.</para>
    ///
    /// <para>Under the hood, the API transforms requests into a format suitable for
    /// the model. The model's output then goes through a parsing stage before becoming
    /// an API response. As a result, the token counts in `usage` will not match one-to-one
    /// with the exact visible content of an API request or response.</para>
    ///
    /// <para>For example, `output_tokens` will be non-zero, even for an empty string
    /// response from Claude.</para>
    ///
    /// <para>Total input tokens in a request is the summation of `input_tokens`,
    /// `cache_creation_input_tokens`, and `cache_read_input_tokens`.</para>
    /// </summary>
    public required BetaUsage Usage
    {
        get { return ModelBase.GetNotNullClass<BetaUsage>(this.RawData, "usage"); }
        init { ModelBase.Set(this._rawData, "usage", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        this.Container?.Validate();
        foreach (var item in this.Content)
        {
            item.Validate();
        }
        this.ContextManagement?.Validate();
        this.Model.Validate();
        if (
            !JsonElement.DeepEquals(
                this.Role,
                JsonSerializer.Deserialize<JsonElement>("\"assistant\"")
            )
        )
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
        this.StopReason?.Validate();
        _ = this.StopSequence;
        if (
            !JsonElement.DeepEquals(
                this.Type,
                JsonSerializer.Deserialize<JsonElement>("\"message\"")
            )
        )
        {
            throw new AnthropicInvalidDataException("Invalid value given for constant");
        }
        this.Usage.Validate();
    }

    public BetaMessage()
    {
        this.Role = JsonSerializer.Deserialize<JsonElement>("\"assistant\"");
        this.Type = JsonSerializer.Deserialize<JsonElement>("\"message\"");
    }

    public BetaMessage(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];

        this.Role = JsonSerializer.Deserialize<JsonElement>("\"assistant\"");
        this.Type = JsonSerializer.Deserialize<JsonElement>("\"message\"");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    BetaMessage(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="BetaMessageFromRaw.FromRawUnchecked"/>
    public static BetaMessage FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class BetaMessageFromRaw : IFromRaw<BetaMessage>
{
    /// <inheritdoc/>
    public BetaMessage FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        BetaMessage.FromRawUnchecked(rawData);
}
